### ISSUE TITLE
Documentation on alternative backend setups?

### ISSUE THREAD

**Issue by wflanagan** [Fullscript/yabeda-activejob#11]
I'm trying to implement this on top of the new SolidQueue adapter, and having some problems. The documentation is rather lacking. 

As people move to this new queue system, it's likely this will increase in need. IF someone can talk me through what they can, I'll be happy to document my process back in a pull request. 

I am also running in Kubernetes, and happy to share docs on that part as well.

**Comment by rosa** [comment]
Hey @wflanagan, what problems are you having? We're running this just fine with Solid Queue by following the same instructions as for Resque, since this is intended to produce metrics at the Active Job level and subscribes only to Active Job events. 

```ruby
# config/initializers/yabeda.rb or elsewhere
Yabeda::ActiveJob.install!
```

**Comment by andrewmarkle** [comment]
I'm going to close then but feel free to re-open if it's still unclear.

**Comment by wflanagan** [comment]
@rosa @andrewmarkle sorry for the delay, i didn't see the notification on this previously. We sorted this out and it's working great. Sorry for the lack of communication.

**Comment by rosa** [comment]
No worries at all! Glad to know you sorted it out 😊
