### ISSUE TITLE
job_latency breaks with Rails 7.2

### ISSUE THREAD

**Issue by mattbnz** [Fullscript/yabeda-activejob#13]
Rails 7.2 breaks the yabeda-activejob instrumentation whenever a job is performed because the semantics of the timestamp returned by ActiveSupport::Notifications::Event changed from milliseconds to seconds! 

The relevant change in ActiveSupport seems to be https://github.com/rails/rails/commit/de779f2bf7f8537ad7097f2568e1936daedba84f

FWIW, by my reading of the Ruby docs, passing a timestamp to Time.parse is not really supported, the fact it worked when the timestamp was in milliseconds seems to be good luck?

**Comment by andrewmarkle** [comment]
closed by: https://github.com/Fullscript/yabeda-activejob/pull/12
